name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "now"
database_id = "3578383a-2db3-4efb-ba7c-5926b363899b"
